package milkyChain.Entity;
// Generated Mar 25, 2022 9:17:47 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerBillTable generated by hbm2java
 */
@Entity
@Table(name = "customer_bill_table", catalog = "milk_management")
public class CustomerBillTable implements java.io.Serializable {

	private Integer customerBillId;
	private CustomerInfoTable customerInfoTable;
	private Date customerBillDateTime;
	private String customerBillForMonth;
	private int totalOrderDays;
	private int totalQuantity;
	private int totalAmountRs;
	private String customerBillStatus;

	public CustomerBillTable() {
	}

	public CustomerBillTable(CustomerInfoTable customerInfoTable, Date customerBillDateTime,
			String customerBillForMonth, int totalOrderDays, int totalQuantity, int totalAmountRs,
			String customerBillStatus) {
		this.customerInfoTable = customerInfoTable;
		this.customerBillDateTime = customerBillDateTime;
		this.customerBillForMonth = customerBillForMonth;
		this.totalOrderDays = totalOrderDays;
		this.totalQuantity = totalQuantity;
		this.totalAmountRs = totalAmountRs;
		this.customerBillStatus = customerBillStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_bill_id", unique = true, nullable = false)
	public Integer getCustomerBillId() {
		return this.customerBillId;
	}

	public void setCustomerBillId(Integer customerBillId) {
		this.customerBillId = customerBillId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public CustomerInfoTable getCustomerInfoTable() {
		return this.customerInfoTable;
	}

	public void setCustomerInfoTable(CustomerInfoTable customerInfoTable) {
		this.customerInfoTable = customerInfoTable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "customer_bill_date_time", nullable = false, length = 19)
	public Date getCustomerBillDateTime() {
		return this.customerBillDateTime;
	}

	public void setCustomerBillDateTime(Date customerBillDateTime) {
		this.customerBillDateTime = customerBillDateTime;
	}

	@Column(name = "customer_bill_for_month", nullable = false, length = 100)
	public String getCustomerBillForMonth() {
		return this.customerBillForMonth;
	}

	public void setCustomerBillForMonth(String customerBillForMonth) {
		this.customerBillForMonth = customerBillForMonth;
	}

	@Column(name = "total_order_days", nullable = false)
	public int getTotalOrderDays() {
		return this.totalOrderDays;
	}

	public void setTotalOrderDays(int totalOrderDays) {
		this.totalOrderDays = totalOrderDays;
	}

	@Column(name = "total_quantity", nullable = false)
	public int getTotalQuantity() {
		return this.totalQuantity;
	}

	public void setTotalQuantity(int totalQuantity) {
		this.totalQuantity = totalQuantity;
	}

	@Column(name = "total_amount_rs", nullable = false)
	public int getTotalAmountRs() {
		return this.totalAmountRs;
	}

	public void setTotalAmountRs(int totalAmountRs) {
		this.totalAmountRs = totalAmountRs;
	}

	@Column(name = "customer_bill_status", nullable = false, length = 100)
	public String getCustomerBillStatus() {
		return this.customerBillStatus;
	}

	public void setCustomerBillStatus(String customerBillStatus) {
		this.customerBillStatus = customerBillStatus;
	}

}
