package milkyChain.Entity;
// Generated Mar 25, 2022 9:17:47 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MilkProductionTable generated by hbm2java
 */
@Entity
@Table(name = "milk_production_table", catalog = "milk_management")
public class MilkProductionTable implements java.io.Serializable {

	private Integer productId;
	private String productName;
	private String milkType;
	private int productionPerDayLiter;
	private int pricePerLiter;
	private List<OrderTable> orderTables;
	private List<SubscriptionTable> subscriptionTables;

	public MilkProductionTable() {
	}

	public MilkProductionTable(String productName, String milkType, int productionPerDayLiter, int pricePerLiter) {
		this.productName = productName;
		this.milkType = milkType;
		this.productionPerDayLiter = productionPerDayLiter;
		this.pricePerLiter = pricePerLiter;
	}

	public MilkProductionTable(String productName, String milkType, int productionPerDayLiter, int pricePerLiter,
			List<OrderTable> orderTables, List<SubscriptionTable> subscriptionTables) {
		this.productName = productName;
		this.milkType = milkType;
		this.productionPerDayLiter = productionPerDayLiter;
		this.pricePerLiter = pricePerLiter;
		this.orderTables = orderTables;
		this.subscriptionTables = subscriptionTables;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_id", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "product_name", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "milk_type", nullable = false, length = 100)
	public String getMilkType() {
		return this.milkType;
	}

	public void setMilkType(String milkType) {
		this.milkType = milkType;
	}

	@Column(name = "production_per_day_liter", nullable = false)
	public int getProductionPerDayLiter() {
		return this.productionPerDayLiter;
	}

	public void setProductionPerDayLiter(int productionPerDayLiter) {
		this.productionPerDayLiter = productionPerDayLiter;
	}

	@Column(name = "price_per_liter", nullable = false)
	public int getPricePerLiter() {
		return this.pricePerLiter;
	}

	public void setPricePerLiter(int pricePerLiter) {
		this.pricePerLiter = pricePerLiter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "milkProductionTable")
	public List<OrderTable> getOrderTables() {
		return this.orderTables;
	}

	public void setOrderTables(List<OrderTable> orderTables) {
		this.orderTables = orderTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "milkProductionTable")
	public List<SubscriptionTable> getSubscriptionTables() {
		return this.subscriptionTables;
	}

	public void setSubscriptionTables(List<SubscriptionTable> subscriptionTables) {
		this.subscriptionTables = subscriptionTables;
	}

}
