package milkyChain.Entity;
// Generated Mar 25, 2022 9:17:47 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NonDeliverRecord generated by hbm2java
 */
@Entity
@Table(name = "non_deliver_record", catalog = "milk_management")
public class NonDeliverRecord implements java.io.Serializable {

	private Integer nonDeliverRecordId;
	private SubscriptionTable subscriptionTable;
	private Date nonDeliverRecordDate;
	private String nonDeliverRecordStatus;

	public NonDeliverRecord() {
	}

	public NonDeliverRecord(SubscriptionTable subscriptionTable, Date nonDeliverRecordDate,
			String nonDeliverRecordStatus) {
		this.subscriptionTable = subscriptionTable;
		this.nonDeliverRecordDate = nonDeliverRecordDate;
		this.nonDeliverRecordStatus = nonDeliverRecordStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "non_deliver_record_id", unique = true, nullable = false)
	public Integer getNonDeliverRecordId() {
		return this.nonDeliverRecordId;
	}

	public void setNonDeliverRecordId(Integer nonDeliverRecordId) {
		this.nonDeliverRecordId = nonDeliverRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subscription_id", nullable = false)
	public SubscriptionTable getSubscriptionTable() {
		return this.subscriptionTable;
	}

	public void setSubscriptionTable(SubscriptionTable subscriptionTable) {
		this.subscriptionTable = subscriptionTable;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "non_deliver_record_date", nullable = false, length = 10)
	public Date getNonDeliverRecordDate() {
		return this.nonDeliverRecordDate;
	}

	public void setNonDeliverRecordDate(Date nonDeliverRecordDate) {
		this.nonDeliverRecordDate = nonDeliverRecordDate;
	}

	@Column(name = "non_deliver_record_status", nullable = false, length = 100)
	public String getNonDeliverRecordStatus() {
		return this.nonDeliverRecordStatus;
	}

	public void setNonDeliverRecordStatus(String nonDeliverRecordStatus) {
		this.nonDeliverRecordStatus = nonDeliverRecordStatus;
	}

}
