package milkyChain.Entity;
// Generated Mar 25, 2022 9:17:47 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderTable generated by hbm2java
 */
@Entity
@Table(name = "order_table", catalog = "milk_management")
public class OrderTable implements java.io.Serializable {

	private Integer orderId;
	private CustomerInfoTable customerInfoTable;
	private MilkProductionTable milkProductionTable;
	private SupplierInfoTable supplierInfoTable;
	private Date orderDate;
	private int orderQuantity;
	private Date orderDeliveryDate;
	private String orderStatus;
	private int totalOrderCost;

	public OrderTable() {
	}

	public OrderTable(CustomerInfoTable customerInfoTable, MilkProductionTable milkProductionTable,
			SupplierInfoTable supplierInfoTable, Date orderDate, int orderQuantity, Date orderDeliveryDate,
			String orderStatus, int totalOrderCost) {
		this.customerInfoTable = customerInfoTable;
		this.milkProductionTable = milkProductionTable;
		this.supplierInfoTable = supplierInfoTable;
		this.orderDate = orderDate;
		this.orderQuantity = orderQuantity;
		this.orderDeliveryDate = orderDeliveryDate;
		this.orderStatus = orderStatus;
		this.totalOrderCost = totalOrderCost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public CustomerInfoTable getCustomerInfoTable() {
		return this.customerInfoTable;
	}

	public void setCustomerInfoTable(CustomerInfoTable customerInfoTable) {
		this.customerInfoTable = customerInfoTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public MilkProductionTable getMilkProductionTable() {
		return this.milkProductionTable;
	}

	public void setMilkProductionTable(MilkProductionTable milkProductionTable) {
		this.milkProductionTable = milkProductionTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id", nullable = false)
	public SupplierInfoTable getSupplierInfoTable() {
		return this.supplierInfoTable;
	}

	public void setSupplierInfoTable(SupplierInfoTable supplierInfoTable) {
		this.supplierInfoTable = supplierInfoTable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "order_quantity", nullable = false)
	public int getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(int orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_delivery_date", nullable = false, length = 19)
	public Date getOrderDeliveryDate() {
		return this.orderDeliveryDate;
	}

	public void setOrderDeliveryDate(Date orderDeliveryDate) {
		this.orderDeliveryDate = orderDeliveryDate;
	}

	@Column(name = "order_status", nullable = false, length = 100)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "total_order_cost", nullable = false)
	public int getTotalOrderCost() {
		return this.totalOrderCost;
	}

	public void setTotalOrderCost(int totalOrderCost) {
		this.totalOrderCost = totalOrderCost;
	}

}
