package milkyChain.Entity;
// Generated Mar 25, 2022 9:17:47 PM by Hibernate Tools 3.5.0.Final


import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SupplierInfoTable generated by hbm2java
 */
@Entity
@Table(name = "supplier_info_table", catalog = "milk_management", uniqueConstraints = {
		@UniqueConstraint(columnNames = "supplier_username"), @UniqueConstraint(columnNames = "supplier_email"),
		@UniqueConstraint(columnNames = "supplier_password") })
public class SupplierInfoTable implements java.io.Serializable {

	private Integer supplierId;
	private String supplierFname;
	private String supplierLname;
	private String supplierAddress;
	private String supplierMobileNo;
	private String supplierEmail;
	private String supplierUsername;
	private String supplierPassword;
	private String supplierWorkArea;
	private int supplerWorkAreaPincode;
	private List<OrderTable> orderTables;
	private List<SubscriptionTable> subscriptionTables;

	public SupplierInfoTable() {
	}

	public SupplierInfoTable(String supplierFname, String supplierLname, String supplierAddress,
			String supplierMobileNo, String supplierEmail, String supplierUsername, String supplierPassword,
			String supplierWorkArea, int supplerWorkAreaPincode) {
		this.supplierFname = supplierFname;
		this.supplierLname = supplierLname;
		this.supplierAddress = supplierAddress;
		this.supplierMobileNo = supplierMobileNo;
		this.supplierEmail = supplierEmail;
		this.supplierUsername = supplierUsername;
		this.supplierPassword = supplierPassword;
		this.supplierWorkArea = supplierWorkArea;
		this.supplerWorkAreaPincode = supplerWorkAreaPincode;
	}

	public SupplierInfoTable(String supplierFname, String supplierLname, String supplierAddress,
			String supplierMobileNo, String supplierEmail, String supplierUsername, String supplierPassword,
			String supplierWorkArea, int supplerWorkAreaPincode, List<OrderTable> orderTables,
			List<SubscriptionTable> subscriptionTables) {
		this.supplierFname = supplierFname;
		this.supplierLname = supplierLname;
		this.supplierAddress = supplierAddress;
		this.supplierMobileNo = supplierMobileNo;
		this.supplierEmail = supplierEmail;
		this.supplierUsername = supplierUsername;
		this.supplierPassword = supplierPassword;
		this.supplierWorkArea = supplierWorkArea;
		this.supplerWorkAreaPincode = supplerWorkAreaPincode;
		this.orderTables = orderTables;
		this.subscriptionTables = subscriptionTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "supplier_id", unique = true, nullable = false)
	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	@Column(name = "supplier_fname", nullable = false, length = 100)
	public String getSupplierFname() {
		return this.supplierFname;
	}

	public void setSupplierFname(String supplierFname) {
		this.supplierFname = supplierFname;
	}

	@Column(name = "supplier_lname", nullable = false, length = 100)
	public String getSupplierLname() {
		return this.supplierLname;
	}

	public void setSupplierLname(String supplierLname) {
		this.supplierLname = supplierLname;
	}

	@Column(name = "supplier_address", nullable = false, length = 100)
	public String getSupplierAddress() {
		return this.supplierAddress;
	}

	public void setSupplierAddress(String supplierAddress) {
		this.supplierAddress = supplierAddress;
	}

	@Column(name = "supplier_mobile_no", nullable = false, length = 100)
	public String getSupplierMobileNo() {
		return this.supplierMobileNo;
	}

	public void setSupplierMobileNo(String supplierMobileNo) {
		this.supplierMobileNo = supplierMobileNo;
	}

	@Column(name = "supplier_email", unique = true, nullable = false, length = 100)
	public String getSupplierEmail() {
		return this.supplierEmail;
	}

	public void setSupplierEmail(String supplierEmail) {
		this.supplierEmail = supplierEmail;
	}

	@Column(name = "supplier_username", unique = true, nullable = false, length = 100)
	public String getSupplierUsername() {
		return this.supplierUsername;
	}

	public void setSupplierUsername(String supplierUsername) {
		this.supplierUsername = supplierUsername;
	}

	@Column(name = "supplier_password", unique = true, nullable = false, length = 100)
	public String getSupplierPassword() {
		return this.supplierPassword;
	}

	public void setSupplierPassword(String supplierPassword) {
		this.supplierPassword = supplierPassword;
	}

	@Column(name = "supplier_work_area", nullable = false, length = 100)
	public String getSupplierWorkArea() {
		return this.supplierWorkArea;
	}

	public void setSupplierWorkArea(String supplierWorkArea) {
		this.supplierWorkArea = supplierWorkArea;
	}

	@Column(name = "suppler_work_area_pincode", nullable = false)
	public int getSupplerWorkAreaPincode() {
		return this.supplerWorkAreaPincode;
	}

	public void setSupplerWorkAreaPincode(int supplerWorkAreaPincode) {
		this.supplerWorkAreaPincode = supplerWorkAreaPincode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplierInfoTable")
	public List<OrderTable> getOrderTables() {
		return this.orderTables;
	}

	public void setOrderTables(List<OrderTable> orderTables) {
		this.orderTables = orderTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplierInfoTable")
	public List<SubscriptionTable> getSubscriptionTables() {
		return this.subscriptionTables;
	}

	public void setSubscriptionTables(List<SubscriptionTable> subscriptionTables) {
		this.subscriptionTables = subscriptionTables;
	}

}
